********************************************************************************************************************;    
* Project: Model-based quantification of protein-protein interaction aberrations 
					for exploring dysregulated signalling pathways through pathway maps and gene expression levels
* Program: LUSC_02_EstimationQ_250504_KKK.sas
* Objective: Estimation of Q_1 and Q_0
* Author: Kenta Kevee Kisai
* SAS version: 9.4
* Platform: Windows
* Made: 7 July 2024
* Update: 4 May 2025
* Note: 
********************************************************************************************************************;     
/* 3_LOG */
proc printto log = 'YOUR_PATH_TO_DIRECTORY\3_LOG\LUSC_02_EstimationQ_250504_KKK.txt' new;
run;
/* 4_ADS */
libname ADS 'YOUR_PATH_TO_DIRECTORY\4_ADS';
/* 5_TLF */
libname TLF 'YOUR_PATH_TO_DIRECTORY\5_TLF';
/* Execution time */
data _null_;
	option timezone = 'asia/tokyo';
	datetime = datetime ();
	put datetime nldatm.; 
run;

* ------------------------------------------------------------------------------------------------------------------------------------------------------- *;       
* Estimate Q_1 and Q_0 for each PPI in the mTOR signalling pathway map
	* Input: ADS.LUSC_ADX_&PPI. 
	* Output: ADS.LUSC_ADQ_&PPI. 
* ------------------------------------------------------------------------------------------------------------------------------------------------------- *;
/* Grb10_R */
/*** mTORC1_Grb10 ***/
data mTORC1_Grb10;
	set ADS.LUSC_ADX_mTORC1_Grb10;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC1_Grb10;
	set mTORC1_Grb10;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC1_Grb10;
	set mTORC1_Grb10 end = last;
    	if last then output;
run;
data mTORC1_Grb10;
	set mTORC1_Grb10;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Grb10_R;
	merge mTORC1_Grb10;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* R_IRS1 */
data ADS.LUSC_ADQ_R_IRS1;
	set ADS.LUSC_ADX_R_IRS1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_R_IRS1;
	set ADS.LUSC_ADQ_R_IRS1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_R_IRS1;
	set ADS.LUSC_ADQ_R_IRS1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_R_IRS1;
	set ADS.LUSC_ADQ_R_IRS1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* S6K_IRS1 */
/*** mTORC1_S6K ***/
data mTORC1_S6K;
	set ADS.LUSC_ADX_mTORC1_S6K;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K end = last;
    	if last then output;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_S6K_IRS1;
	merge mTORC1_S6K;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* IRS1_PI3K */
/*** R_IRS1 ***/
data R_IRS1;
	set ADS.LUSC_ADX_R_IRS1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data R_IRS1;
	set R_IRS1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data R_IRS1;
	set R_IRS1 end = last;
    	if last then output;
run;
data R_IRS1;
	set R_IRS1;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** S6K_IRS1 ***/
data S6K_IRS1;
	set ADS.LUSC_ADX_S6K_IRS1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data S6K_IRS1;
	set S6K_IRS1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data S6K_IRS1;
	set S6K_IRS1 end = last;
    	if last then output;
run;
data S6K_IRS1;
	set S6K_IRS1;
		Q_1_B = 1 - SUM_Q_1/SUM_N_1;
		Q_0_B = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_IRS1_PI3K;
	merge R_IRS1 S6K_IRS1;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* PI3K_mTORC2 */
/*** IRS1_PI3K ***/
data IRS1_PI3K;
	set ADS.LUSC_ADX_IRS1_PI3K;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data IRS1_PI3K;
	set IRS1_PI3K;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data IRS1_PI3K;
	set IRS1_PI3K end = last;
    	if last then output;
run;
data IRS1_PI3K;
	set IRS1_PI3K;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_PI3K_mTORC2;
	merge IRS1_PI3K;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* PDK1_Akt */
data ADS.LUSC_ADQ_PDK1_Akt;
	set ADS.LUSC_ADX_PDK1_Akt;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_PDK1_Akt;
	set ADS.LUSC_ADQ_PDK1_Akt;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_PDK1_Akt;
	set ADS.LUSC_ADQ_PDK1_Akt end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_PDK1_Akt;
	set ADS.LUSC_ADQ_PDK1_Akt;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Akt_IKKA */
/*** PDK1_Akt ***/
data PDK1_Akt;
	set ADS.LUSC_ADX_PDK1_Akt;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data PDK1_Akt;
	set PDK1_Akt;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data PDK1_Akt;
	set PDK1_Akt end = last;
    	if last then output;
run;
data PDK1_Akt;
	set PDK1_Akt;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** mTORC2_Akt ***/
data mTORC2_Akt;
	set ADS.LUSC_ADX_mTORC2_Akt;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC2_Akt;
	set mTORC2_Akt;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC2_Akt;
	set mTORC2_Akt end = last;
    	if last then output;
run;
data mTORC2_Akt;
	set mTORC2_Akt;
		Q_1_B = SUM_Q_1/SUM_N_1;
		Q_0_B = SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Akt_IKKA;
	merge PDK1_Akt mTORC2_Akt;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* IKKA_mTORC2 */
/*** Akt_IKKA ***/
data Akt_IKKA;
	set ADS.LUSC_ADX_Akt_IKKA;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Akt_IKKA;
	set Akt_IKKA;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Akt_IKKA;
	set Akt_IKKA end = last;
    	if last then output;
run;
data Akt_IKKA;
	set Akt_IKKA;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_IKKA_mTORC2;
	merge Akt_IKKA;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC2_Rho */
/*** PI3K_mTORC2 ***/
data PI3K_mTORC2;
	set ADS.LUSC_ADX_PI3K_mTORC2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data PI3K_mTORC2;
	set PI3K_mTORC2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data PI3K_mTORC2;
	set PI3K_mTORC2 end = last;
    	if last then output;
run;
data PI3K_mTORC2;
	set PI3K_mTORC2;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** IKKA_mTORC2 ***/
data IKKA_mTORC2;
	set ADS.LUSC_ADX_IKKA_mTORC2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data IKKA_mTORC2;
	set IKKA_mTORC2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data IKKA_mTORC2;
	set IKKA_mTORC2 end = last;
    	if last then output;
run;
data IKKA_mTORC2;
	set IKKA_mTORC2;
		Q_1_B = SUM_Q_1/SUM_N_1;
		Q_0_B = SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** S6K_mTORC2 ***/
data S6K_mTORC2;
	set ADS.LUSC_ADX_S6K_mTORC2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data S6K_mTORC2;
	set S6K_mTORC2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data S6K_mTORC2;
	set S6K_mTORC2 end = last;
    	if last then output;
run;
data S6K_mTORC2;
	set S6K_mTORC2;
		Q_1_C = 1 - SUM_Q_1/SUM_N_1;
		Q_0_C = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_C Q_0_C;
run;
/*** Deptor_mTORC2 ***/
data Deptor_mTORC2;
	set ADS.LUSC_ADX_Deptor_mTORC2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Deptor_mTORC2;
	set Deptor_mTORC2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Deptor_mTORC2;
	set Deptor_mTORC2 end = last;
    	if last then output;
run;
data Deptor_mTORC2;
	set Deptor_mTORC2;
		Q_1_D = 1 - SUM_Q_1/SUM_N_1;
		Q_0_D = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_D Q_0_D;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC2_Rho;
	merge PI3K_mTORC2 IKKA_mTORC2 S6K_mTORC2 Deptor_mTORC2;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D)/4;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D)/4;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC2_PKC */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC2_PKC;
	merge PI3K_mTORC2 IKKA_mTORC2 S6K_mTORC2 Deptor_mTORC2;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D)/4;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D)/4;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC2_SGK1 */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC2_SGK1;
	merge PI3K_mTORC2 IKKA_mTORC2 S6K_mTORC2 Deptor_mTORC2;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D)/4;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D)/4;
	keep Q_1_HAT Q_0_HAT;
run;
/* R_Grb2 */
data ADS.LUSC_ADQ_R_Grb2;
	set ADS.LUSC_ADX_R_Grb2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_R_Grb2;
	set ADS.LUSC_ADQ_R_Grb2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_R_Grb2;
	set ADS.LUSC_ADQ_R_Grb2 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_R_Grb2;
	set ADS.LUSC_ADQ_R_Grb2;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Grb2_SOS */
/*** R_Grb2 ***/
data R_Grb2;
	set ADS.LUSC_ADX_R_Grb2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data R_Grb2;
	set R_Grb2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data R_Grb2;
	set R_Grb2 end = last;
    	if last then output;
run;
data R_Grb2;
	set R_Grb2;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Grb2_SOS;
	merge R_Grb2;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* SOS_Ras */
/*** Grb2_SOS ***/
data Grb2_SOS;
	set ADS.LUSC_ADX_Grb2_SOS;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Grb2_SOS;
	set Grb2_SOS;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Grb2_SOS;
	set Grb2_SOS end = last;
    	if last then output;
run;
data Grb2_SOS;
	set Grb2_SOS;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_SOS_Ras;
	merge Grb2_SOS;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* Ras_Raf */
/*** SOS_Ras ***/
data SOS_Ras;
	set ADS.LUSC_ADX_SOS_Ras;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data SOS_Ras;
	set SOS_Ras;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data SOS_Ras;
	set SOS_Ras end = last;
    	if last then output;
run;
data SOS_Ras;
	set SOS_Ras;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Ras_Raf;
	merge SOS_Ras;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* Raf_MEK */
/*** Ras_Raf ***/
data Ras_Raf;
	set ADS.LUSC_ADX_Ras_Raf;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Ras_Raf;
	set Ras_Raf;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Ras_Raf;
	set Ras_Raf end = last;
    	if last then output;
run;
data Ras_Raf;
	set Ras_Raf;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Raf_MEK;
	merge Ras_Raf;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* MEK_ERK1 */
/*** Raf_MEK ***/
data Raf_MEK;
	set ADS.LUSC_ADX_Raf_MEK;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Raf_MEK;
	set Raf_MEK;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Raf_MEK;
	set Raf_MEK end = last;
    	if last then output;
run;
data Raf_MEK;
	set Raf_MEK;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_MEK_ERK1;
	merge Raf_MEK;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* ERK1_RSK */
/*** MEK_ERK1 ***/
data MEK_ERK1;
	set ADS.LUSC_ADX_MEK_ERK1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data MEK_ERK1;
	set MEK_ERK1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data MEK_ERK1;
	set MEK_ERK1 end = last;
    	if last then output;
run;
data MEK_ERK1;
	set MEK_ERK1;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_ERK1_RSK;
	merge MEK_ERK1;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* TNFR_IKKB */
data ADS.LUSC_ADQ_TNFR_IKKB;
	set ADS.LUSC_ADX_TNFR_IKKB;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_TNFR_IKKB;
	set ADS.LUSC_ADQ_TNFR_IKKB;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_TNFR_IKKB;
	set ADS.LUSC_ADQ_TNFR_IKKB end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_TNFR_IKKB;
	set ADS.LUSC_ADQ_TNFR_IKKB;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Frizzled_Dvl */
data ADS.LUSC_ADQ_Frizzled_Dvl;
	set ADS.LUSC_ADX_Frizzled_Dvl;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_Frizzled_Dvl;
	set ADS.LUSC_ADQ_Frizzled_Dvl;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_Frizzled_Dvl;
	set ADS.LUSC_ADQ_Frizzled_Dvl end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_Frizzled_Dvl;
	set ADS.LUSC_ADQ_Frizzled_Dvl;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Dvl_GSK3B */
/*** Frizzled_Dvl ***/
data Frizzled_Dvl;
	set ADS.LUSC_ADX_Frizzled_Dvl;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Frizzled_Dvl;
	set Frizzled_Dvl;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Frizzled_Dvl;
	set Frizzled_Dvl end = last;
    	if last then output;
run;
data Frizzled_Dvl;
	set Frizzled_Dvl;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Dvl_GSK3B;
	merge Frizzled_Dvl;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* STRAD_AMPK */
data ADS.LUSC_ADQ_STRAD_AMPK;
	set ADS.LUSC_ADX_STRAD_AMPK;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_STRAD_AMPK;
	set ADS.LUSC_ADQ_STRAD_AMPK;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_STRAD_AMPK;
	set ADS.LUSC_ADQ_STRAD_AMPK end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_STRAD_AMPK;
	set ADS.LUSC_ADQ_STRAD_AMPK;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* ERK1_TSC1 */
/*** MEK_ERK1 ***/
data MEK_ERK1;
	set ADS.LUSC_ADX_MEK_ERK1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data MEK_ERK1;
	set MEK_ERK1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data MEK_ERK1;
	set MEK_ERK1 end = last;
    	if last then output;
run;
data MEK_ERK1;
	set MEK_ERK1;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_ERK1_TSC1;
	merge MEK_ERK1;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* RSK_TSC1 */
/*** ERK1_RSK ***/
data ERK1_RSK;
	set ADS.LUSC_ADX_ERK1_RSK;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ERK1_RSK;
	set ERK1_RSK;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ERK1_RSK;
	set ERK1_RSK end = last;
    	if last then output;
run;
data ERK1_RSK;
	set ERK1_RSK;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_RSK_TSC1;
	merge ERK1_RSK;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* IKKB_TSC1 */
/*** TNFR_IKKB ***/
data TNFR_IKKB;
	set ADS.LUSC_ADX_TNFR_IKKB;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data TNFR_IKKB;
	set TNFR_IKKB;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data TNFR_IKKB;
	set TNFR_IKKB end = last;
    	if last then output;
run;
data TNFR_IKKB;
	set TNFR_IKKB;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_IKKB_TSC1;
	merge TNFR_IKKB;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* GSK3B_TSC1 */
/*** Dvl_GSK3B ***/
data Dvl_GSK3B;
	set ADS.LUSC_ADX_Dvl_GSK3B;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Dvl_GSK3B;
	set Dvl_GSK3B;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Dvl_GSK3B;
	set Dvl_GSK3B end = last;
    	if last then output;
run;
data Dvl_GSK3B;
	set Dvl_GSK3B;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_GSK3B_TSC1;
	merge Dvl_GSK3B;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* REDD1_TSC1 */
data ADS.LUSC_ADQ_REDD1_TSC1;
	set ADS.LUSC_ADX_REDD1_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_REDD1_TSC1;
	set ADS.LUSC_ADQ_REDD1_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_REDD1_TSC1;
	set ADS.LUSC_ADQ_REDD1_TSC1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_REDD1_TSC1;
	set ADS.LUSC_ADQ_REDD1_TSC1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* AMPK_TSC1 */
data ADS.LUSC_ADQ_AMPK_TSC1;
	set ADS.LUSC_ADX_AMPK_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_AMPK_TSC1;
	set ADS.LUSC_ADQ_AMPK_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_AMPK_TSC1;
	set ADS.LUSC_ADQ_AMPK_TSC1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_AMPK_TSC1;
	set ADS.LUSC_ADQ_AMPK_TSC1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Akt_TSC1 */
/*** PDK1_Akt ***/
data PDK1_Akt;
	set ADS.LUSC_ADX_PDK1_Akt;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data PDK1_Akt;
	set PDK1_Akt;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data PDK1_Akt;
	set PDK1_Akt end = last;
    	if last then output;
run;
data PDK1_Akt;
	set PDK1_Akt;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** mTORC2_Akt ***/
data mTORC2_Akt;
	set ADS.LUSC_ADX_mTORC2_Akt;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC2_Akt;
	set mTORC2_Akt;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC2_Akt;
	set mTORC2_Akt end = last;
    	if last then output;
run;
data mTORC2_Akt;
	set mTORC2_Akt;
		Q_1_B = SUM_Q_1/SUM_N_1;
		Q_0_B = SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Akt_TSC1;
	merge PDK1_Akt mTORC2_Akt;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* Akt_PRAS40 */
/*** Integration ***/
data ADS.LUSC_ADQ_Akt_PRAS40;
	merge PDK1_Akt mTORC2_Akt;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* IKKA_mTORC1 */
/*** Integration ***/
data ADS.LUSC_ADQ_IKKA_mTORC1;
	merge Akt_IKKA;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* TSC1_Rheb */
/*** AMPK_TSC1 ***/
data AMPK_TSC1;
	set ADS.LUSC_ADX_AMPK_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data AMPK_TSC1;
	set AMPK_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data AMPK_TSC1;
	set AMPK_TSC1 end = last;
    	if last then output;
run;
data AMPK_TSC1;
	set AMPK_TSC1;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** REDD1_TSC1 ***/
data REDD1_TSC1;
	set ADS.LUSC_ADX_REDD1_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data REDD1_TSC1;
	set REDD1_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data REDD1_TSC1;
	set REDD1_TSC1 end = last;
    	if last then output;
run;
data REDD1_TSC1;
	set REDD1_TSC1;
		Q_1_B = SUM_Q_1/SUM_N_1;
		Q_0_B = SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** GSK3B_TSC1 ***/
data GSK3B_TSC1;
	set ADS.LUSC_ADX_GSK3B_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data GSK3B_TSC1;
	set GSK3B_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data GSK3B_TSC1;
	set GSK3B_TSC1 end = last;
    	if last then output;
run;
data GSK3B_TSC1;
	set GSK3B_TSC1;
		Q_1_C = SUM_Q_1/SUM_N_1;
		Q_0_C = SUM_Q_0/SUM_N_0;
	keep Q_1_C Q_0_C;
run;
/*** IKKB_TSC1 ***/
data IKKB_TSC1;
	set ADS.LUSC_ADX_IKKB_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data IKKB_TSC1;
	set IKKB_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data IKKB_TSC1;
	set IKKB_TSC1 end = last;
    	if last then output;
run;
data IKKB_TSC1;
	set IKKB_TSC1;
		Q_1_D = 1 - SUM_Q_1/SUM_N_1;
		Q_0_D = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_D Q_0_D;
run;
/*** RSK_TSC1 ***/
data RSK_TSC1;
	set ADS.LUSC_ADX_RSK_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data RSK_TSC1;
	set RSK_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data RSK_TSC1;
	set RSK_TSC1 end = last;
    	if last then output;
run;
data RSK_TSC1;
	set RSK_TSC1;
		Q_1_E = 1 - SUM_Q_1/SUM_N_1;
		Q_0_E = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_E Q_0_E;
run;
/*** ERK1_TSC1 ***/
data ERK1_TSC1;
	set ADS.LUSC_ADX_ERK1_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ERK1_TSC1;
	set ERK1_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ERK1_TSC1;
	set ERK1_TSC1 end = last;
    	if last then output;
run;
data ERK1_TSC1;
	set ERK1_TSC1;
		Q_1_F = 1 - SUM_Q_1/SUM_N_1;
		Q_0_F = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_F Q_0_F;
run;
/*** Akt_TSC1 ***/
data Akt_TSC1;
	set ADS.LUSC_ADX_Akt_TSC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Akt_TSC1;
	set Akt_TSC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Akt_TSC1;
	set Akt_TSC1 end = last;
    	if last then output;
run;
data Akt_TSC1;
	set Akt_TSC1;
		Q_1_G = 1 - SUM_Q_1/SUM_N_1;
		Q_0_G = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_G Q_0_G;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_TSC1_Rheb;
	merge AMPK_TSC1 REDD1_TSC1 GSK3B_TSC1 IKKB_TSC1 RSK_TSC1 ERK1_TSC1 Akt_TSC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F + Q_1_G)/7;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F + Q_0_G)/7;
	keep Q_1_HAT Q_0_HAT;
run;
/* Rheb_mTORC1 */
/*** TSC1_Rheb ***/
data TSC1_Rheb;
	set ADS.LUSC_ADX_TSC1_Rheb;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data TSC1_Rheb;
	set TSC1_Rheb;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data TSC1_Rheb;
	set TSC1_Rheb end = last;
    	if last then output;
run;
data TSC1_Rheb;
	set TSC1_Rheb;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Rheb_mTORC1;
	merge TSC1_Rheb;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* AMPK_mTORC1 */
data ADS.LUSC_ADQ_AMPK_mTORC1;
	set ADS.LUSC_ADX_AMPK_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_AMPK_mTORC1;
	set ADS.LUSC_ADQ_AMPK_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_AMPK_mTORC1;
	set ADS.LUSC_ADQ_AMPK_mTORC1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_AMPK_mTORC1;
	set ADS.LUSC_ADQ_AMPK_mTORC1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* SLC38A9_Ragulator */
data ADS.LUSC_ADQ_SLC38A9_Ragulator;
	set ADS.LUSC_ADX_SLC38A9_Ragulator;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_SLC38A9_Ragulator;
	set ADS.LUSC_ADQ_SLC38A9_Ragulator;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_SLC38A9_Ragulator;
	set ADS.LUSC_ADQ_SLC38A9_Ragulator end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_SLC38A9_Ragulator;
	set ADS.LUSC_ADQ_SLC38A9_Ragulator;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* VATPase_Ragulator */
data ADS.LUSC_ADQ_VATPase_Ragulator;
	set ADS.LUSC_ADX_VATPase_Ragulator;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_VATPase_Ragulator;
	set ADS.LUSC_ADQ_VATPase_Ragulator;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_VATPase_Ragulator;
	set ADS.LUSC_ADQ_VATPase_Ragulator end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_VATPase_Ragulator;
	set ADS.LUSC_ADQ_VATPase_Ragulator;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* FNIP_RagA */
data ADS.LUSC_ADQ_FNIP_RagA;
	set ADS.LUSC_ADX_FNIP_RagA;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_FNIP_RagA;
	set ADS.LUSC_ADQ_FNIP_RagA;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_FNIP_RagA;
	set ADS.LUSC_ADQ_FNIP_RagA end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_FNIP_RagA;
	set ADS.LUSC_ADQ_FNIP_RagA;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Ragulator_RagA */
/*** SLC38A9_Ragulator ***/
data SLC38A9_Ragulator;
	set ADS.LUSC_ADX_SLC38A9_Ragulator;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data SLC38A9_Ragulator;
	set SLC38A9_Ragulator;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data SLC38A9_Ragulator;
	set SLC38A9_Ragulator end = last;
    	if last then output;
run;
data SLC38A9_Ragulator;
	set SLC38A9_Ragulator;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** VATPase_Ragulator ***/
data VATPase_Ragulator;
	set ADS.LUSC_ADX_VATPase_Ragulator;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data VATPase_Ragulator;
	set VATPase_Ragulator;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data VATPase_Ragulator;
	set VATPase_Ragulator end = last;
    	if last then output;
run;
data VATPase_Ragulator;
	set VATPase_Ragulator;
		Q_1_B = SUM_Q_1/SUM_N_1;
		Q_0_B = SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_Ragulator_RagA;
	merge SLC38A9_Ragulator VATPase_Ragulator;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* RagA_mTORC1 */
data ADS.LUSC_ADQ_RagA_mTORC1;
	set ADS.LUSC_ADX_RagA_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_RagA_mTORC1;
	set ADS.LUSC_ADQ_RagA_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_RagA_mTORC1;
	set ADS.LUSC_ADQ_RagA_mTORC1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_RagA_mTORC1;
	set ADS.LUSC_ADQ_RagA_mTORC1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* SESN2_GATOR2 */
data ADS.LUSC_ADQ_SESN2_GATOR2;
	set ADS.LUSC_ADX_SESN2_GATOR2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_SESN2_GATOR2;
	set ADS.LUSC_ADQ_SESN2_GATOR2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_SESN2_GATOR2;
	set ADS.LUSC_ADQ_SESN2_GATOR2 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_SESN2_GATOR2;
	set ADS.LUSC_ADQ_SESN2_GATOR2;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* CASTOR1_GATOR2 */
data ADS.LUSC_ADQ_CASTOR1_GATOR2;
	set ADS.LUSC_ADX_CASTOR1_GATOR2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_CASTOR1_GATOR2;
	set ADS.LUSC_ADQ_CASTOR1_GATOR2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_CASTOR1_GATOR2;
	set ADS.LUSC_ADQ_CASTOR1_GATOR2 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_CASTOR1_GATOR2;
	set ADS.LUSC_ADQ_CASTOR1_GATOR2;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* GATOR2_GATOR1 */
/*** SESN2_GATOR2 ***/
data SESN2_GATOR2;
	set ADS.LUSC_ADX_SESN2_GATOR2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data SESN2_GATOR2;
	set SESN2_GATOR2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data SESN2_GATOR2;
	set SESN2_GATOR2 end = last;
    	if last then output;
run;
data SESN2_GATOR2;
	set SESN2_GATOR2;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** CASTOR1_GATOR2 ***/
data CASTOR1_GATOR2;
	set ADS.LUSC_ADX_CASTOR1_GATOR2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data CASTOR1_GATOR2;
	set CASTOR1_GATOR2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data CASTOR1_GATOR2;
	set CASTOR1_GATOR2 end = last;
    	if last then output;
run;
data CASTOR1_GATOR2;
	set CASTOR1_GATOR2;
		Q_1_B = 1 - SUM_Q_1/SUM_N_1;
		Q_0_B = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_GATOR2_GATOR1;
	merge SESN2_GATOR2 CASTOR1_GATOR2;
		Q_1_HAT = (Q_1_A + Q_1_B)/2;
		Q_0_HAT = (Q_0_A + Q_0_B)/2;
	keep Q_1_HAT Q_0_HAT;
run;
/* GATOR1_RagA */
/*** GATOR2_GATOR1 ***/
data GATOR2_GATOR1;
	set ADS.LUSC_ADX_GATOR2_GATOR1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data GATOR2_GATOR1;
	set GATOR2_GATOR1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data GATOR2_GATOR1;
	set GATOR2_GATOR1 end = last;
    	if last then output;
run;
data GATOR2_GATOR1;
	set GATOR2_GATOR1;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_GATOR1_RagA;
	merge GATOR2_GATOR1;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* Skp2_RagA */
data ADS.LUSC_ADQ_Skp2_RagA;
	set ADS.LUSC_ADX_Skp2_RagA;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_Skp2_RagA;
	set ADS.LUSC_ADQ_Skp2_RagA;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_Skp2_RagA;
	set ADS.LUSC_ADQ_Skp2_RagA end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_Skp2_RagA;
	set ADS.LUSC_ADQ_Skp2_RagA;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* RNF152_RagA */
data ADS.LUSC_ADQ_RNF152_RagA;
	set ADS.LUSC_ADX_RNF152_RagA;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_RNF152_RagA;
	set ADS.LUSC_ADQ_RNF152_RagA;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_RNF152_RagA;
	set ADS.LUSC_ADQ_RNF152_RagA end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_RNF152_RagA;
	set ADS.LUSC_ADQ_RNF152_RagA;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* S6K_mTORC2 */
/*** mTORC1_S6K ***/
data mTORC1_S6K;
	set ADS.LUSC_ADX_mTORC1_S6K;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K end = last;
    	if last then output;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_S6K_mTORC2;
	merge mTORC1_S6K;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_CLIP170 */
/*** RagA_mTORC1 ***/
data RagA_mTORC1;
	set ADS.LUSC_ADX_RagA_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data RagA_mTORC1;
	set RagA_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data RagA_mTORC1;
	set RagA_mTORC1 end = last;
    	if last then output;
run;
data RagA_mTORC1;
	set RagA_mTORC1;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** AMPK_mTORC1 ***/
data AMPK_mTORC1;
	set ADS.LUSC_ADX_AMPK_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data AMPK_mTORC1;
	set AMPK_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data AMPK_mTORC1;
	set AMPK_mTORC1 end = last;
    	if last then output;
run;
data AMPK_mTORC1;
	set AMPK_mTORC1;
		Q_1_B = 1 - SUM_Q_1/SUM_N_1;
		Q_0_B = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_B Q_0_B;
run;
/*** Rheb_mTORC1 ***/
data Rheb_mTORC1;
	set ADS.LUSC_ADX_Rheb_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Rheb_mTORC1;
	set Rheb_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Rheb_mTORC1;
	set Rheb_mTORC1 end = last;
    	if last then output;
run;
data Rheb_mTORC1;
	set Rheb_mTORC1;
		Q_1_C = SUM_Q_1/SUM_N_1;
		Q_0_C = SUM_Q_0/SUM_N_0;
	keep Q_1_C Q_0_C;
run;
/*** PRAS40_mTORC1 ***/
data PRAS40_mTORC1;
	set ADS.LUSC_ADX_PRAS40_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data PRAS40_mTORC1;
	set PRAS40_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data PRAS40_mTORC1;
	set PRAS40_mTORC1 end = last;
    	if last then output;
run;
data PRAS40_mTORC1;
	set PRAS40_mTORC1;
		Q_1_D = 1 - SUM_Q_1/SUM_N_1;
		Q_0_D = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_D Q_0_D;
run;
/*** IKKA_mTORC1 ***/
data IKKA_mTORC1;
	set ADS.LUSC_ADX_IKKA_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data IKKA_mTORC1;
	set IKKA_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data IKKA_mTORC1;
	set IKKA_mTORC1 end = last;
    	if last then output;
run;
data IKKA_mTORC1;
	set IKKA_mTORC1;
		Q_1_E = SUM_Q_1/SUM_N_1;
		Q_0_E = SUM_Q_0/SUM_N_0;
	keep Q_1_E Q_0_E;
run;
/*** Deptor_mTORC1 ***/
data Deptor_mTORC1;
	set ADS.LUSC_ADX_Deptor_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Deptor_mTORC1;
	set Deptor_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Deptor_mTORC1;
	set Deptor_mTORC1 end = last;
    	if last then output;
run;
data Deptor_mTORC1;
	set Deptor_mTORC1;
		Q_1_F = 1 - SUM_Q_1/SUM_N_1;
		Q_0_F = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_F Q_0_F;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_CLIP170;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_Grb10 */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_Grb10;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_Lipin1 */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_Lipin1;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_ATG1 */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_ATG1;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_4EBP */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_4EBP;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC1_S6K */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC1_S6K;
	merge RagA_mTORC1 AMPK_mTORC1 Rheb_mTORC1 PRAS40_mTORC1 IKKA_mTORC1 Deptor_mTORC1;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D + Q_1_E + Q_1_F)/6;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D + Q_0_E + Q_0_F)/6;
	keep Q_1_HAT Q_0_HAT;
run;
/* 4EBP_eIF4E */
/*** mTORC1_4EBP ***/
data mTORC1_4EBP;
	set ADS.LUSC_ADX_mTORC1_4EBP;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC1_4EBP;
	set mTORC1_4EBP;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC1_4EBP;
	set mTORC1_4EBP end = last;
    	if last then output;
run;
data mTORC1_4EBP;
	set mTORC1_4EBP;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_4EBP_eIF4E;
	merge mTORC1_4EBP;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* S6K_eIF4B */
/*** mTORC1_S6K ***/
data mTORC1_S6K;
	set ADS.LUSC_ADX_mTORC1_S6K;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data mTORC1_S6K;
	set mTORC1_S6K end = last;
    	if last then output;
run;
data mTORC1_S6K;
	set mTORC1_S6K;
		Q_1_A = SUM_Q_1/SUM_N_1;
		Q_0_A = SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_S6K_eIF4B;
	merge mTORC1_S6K;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* S6K_S6 */
/*** Integration ***/
data ADS.LUSC_ADQ_S6K_S6;
	merge mTORC1_S6K;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* Deptor_mTORC1 */
data ADS.LUSC_ADQ_Deptor_mTORC1;
	set ADS.LUSC_ADX_Deptor_mTORC1;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_Deptor_mTORC1;
	set ADS.LUSC_ADQ_Deptor_mTORC1;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_Deptor_mTORC1;
	set ADS.LUSC_ADQ_Deptor_mTORC1 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_Deptor_mTORC1;
	set ADS.LUSC_ADQ_Deptor_mTORC1;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* Deptor_mTORC2 */
data ADS.LUSC_ADQ_Deptor_mTORC2;
	set ADS.LUSC_ADX_Deptor_mTORC2;
		if J = 1 then do;
			N_1 = 1;
			if X_1 > X_2 then Q_1 = X_2/X_1;
				else Q_1 = 1;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 > X_2 then Q_0 = X_2/X_1;
				else Q_0 = 1;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data ADS.LUSC_ADQ_Deptor_mTORC2;
	set ADS.LUSC_ADQ_Deptor_mTORC2;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data ADS.LUSC_ADQ_Deptor_mTORC2;
	set ADS.LUSC_ADQ_Deptor_mTORC2 end = last;
    	if last then output;
run;
data ADS.LUSC_ADQ_Deptor_mTORC2;
	set ADS.LUSC_ADQ_Deptor_mTORC2;
		Q_1_HAT = SUM_Q_1/SUM_N_1;
		Q_0_HAT = SUM_Q_0/SUM_N_0;
	keep Q_1_HAT Q_0_HAT;
run;
/* PRAS40_mTORC1 */
/*** Akt_PRAS40 ***/
data Akt_PRAS40;
	set ADS.LUSC_ADX_Akt_PRAS40;
		if J = 1 then do;
			N_1 = 1;
			if X_1 >= X_2 then Q_1 = 1;
				else Q_1 = X_1/X_2;
		end;
		if J = 0 then do;
			N_0 = 1;
			if X_1 >= X_2 then Q_0 = 1;
				else Q_0 = X_1/X_2;
		end;
	keep N_1 Q_1 N_0 Q_0;
run;
data Akt_PRAS40;
	set Akt_PRAS40;
		retain SUM_N_1 0;
			SUM_N_1 + N_1;
    	retain SUM_Q_1 0;
			SUM_Q_1 + Q_1;
		retain SUM_N_0 0;
			SUM_N_0 + N_0;
		retain SUM_Q_0 0;
			SUM_Q_0 + Q_0;
	keep SUM_N_1 SUM_Q_1 SUM_N_0 SUM_Q_0;
run;
data Akt_PRAS40;
	set Akt_PRAS40 end = last;
    	if last then output;
run;
data Akt_PRAS40;
	set Akt_PRAS40;
		Q_1_A = 1 - SUM_Q_1/SUM_N_1;
		Q_0_A = 1 - SUM_Q_0/SUM_N_0;
	keep Q_1_A Q_0_A;
run;
/*** Integration ***/
data ADS.LUSC_ADQ_PRAS40_mTORC1;
	merge Akt_PRAS40;
		Q_1_HAT = (Q_1_A)/1;
		Q_0_HAT = (Q_0_A)/1;
	keep Q_1_HAT Q_0_HAT;
run;
/* mTORC2_Akt */
/*** Integration ***/
data ADS.LUSC_ADQ_mTORC2_Akt;
	merge PI3K_mTORC2 IKKA_mTORC2 S6K_mTORC2 Deptor_mTORC2;
		Q_1_HAT = (Q_1_A + Q_1_B + Q_1_C + Q_1_D)/4;
		Q_0_HAT = (Q_0_A + Q_0_B + Q_0_C + Q_0_D)/4;
	keep Q_1_HAT Q_0_HAT;
run;

* ------------------------------------------------------------------------------------------------------------------------------------------------------- *;
* Integrate the results from each PPI
	* Input: ADS.LUSC_ADQ_&PPI. 
	* Output: TLF.LUSC_ADQ
* ------------------------------------------------------------------------------------------------------------------------------------------------------- *;
data TLF.LUSC_ADQ;
	set ADS.LUSC_ADQ_Grb10_R 
			ADS.LUSC_ADQ_R_IRS1 
			ADS.LUSC_ADQ_S6K_IRS1 
			ADS.LUSC_ADQ_IRS1_PI3K 
			ADS.LUSC_ADQ_PI3K_mTORC2 
			ADS.LUSC_ADQ_PDK1_Akt 
			ADS.LUSC_ADQ_Akt_IKKA 
			ADS.LUSC_ADQ_IKKA_mTORC2 
			ADS.LUSC_ADQ_mTORC2_Rho
			ADS.LUSC_ADQ_mTORC2_PKC 
			ADS.LUSC_ADQ_mTORC2_SGK1
			ADS.LUSC_ADQ_R_Grb2
			ADS.LUSC_ADQ_Grb2_SOS
			ADS.LUSC_ADQ_SOS_Ras
			ADS.LUSC_ADQ_Ras_Raf
			ADS.LUSC_ADQ_Raf_MEK
			ADS.LUSC_ADQ_MEK_ERK1
			ADS.LUSC_ADQ_ERK1_RSK
			ADS.LUSC_ADQ_TNFR_IKKB
			ADS.LUSC_ADQ_Frizzled_Dvl
			ADS.LUSC_ADQ_Dvl_GSK3B
			ADS.LUSC_ADQ_STRAD_AMPK
			ADS.LUSC_ADQ_ERK1_TSC1
			ADS.LUSC_ADQ_RSK_TSC1
			ADS.LUSC_ADQ_IKKB_TSC1
			ADS.LUSC_ADQ_GSK3B_TSC1
			ADS.LUSC_ADQ_REDD1_TSC1
			ADS.LUSC_ADQ_AMPK_TSC1
			ADS.LUSC_ADQ_Akt_TSC1
			ADS.LUSC_ADQ_Akt_PRAS40
			ADS.LUSC_ADQ_IKKA_mTORC1
			ADS.LUSC_ADQ_TSC1_Rheb
			ADS.LUSC_ADQ_Rheb_mTORC1
			ADS.LUSC_ADQ_AMPK_mTORC1
			ADS.LUSC_ADQ_SLC38A9_Ragulator
			ADS.LUSC_ADQ_VATPase_Ragulator
			ADS.LUSC_ADQ_FNIP_RagA
			ADS.LUSC_ADQ_Ragulator_RagA
			ADS.LUSC_ADQ_RagA_mTORC1
			ADS.LUSC_ADQ_SESN2_GATOR2
			ADS.LUSC_ADQ_CASTOR1_GATOR2
			ADS.LUSC_ADQ_GATOR2_GATOR1
			ADS.LUSC_ADQ_GATOR1_RagA
			ADS.LUSC_ADQ_Skp2_RagA
			ADS.LUSC_ADQ_RNF152_RagA
			ADS.LUSC_ADQ_S6K_mTORC2
			ADS.LUSC_ADQ_mTORC1_CLIP170
			ADS.LUSC_ADQ_mTORC1_Grb10
			ADS.LUSC_ADQ_mTORC1_Lipin1
			ADS.LUSC_ADQ_mTORC1_ATG1
			ADS.LUSC_ADQ_mTORC1_4EBP
			ADS.LUSC_ADQ_mTORC1_S6K
			ADS.LUSC_ADQ_4EBP_eIF4E
			ADS.LUSC_ADQ_S6K_eIF4B
			ADS.LUSC_ADQ_S6K_S6
			ADS.LUSC_ADQ_Deptor_mTORC1
			ADS.LUSC_ADQ_Deptor_mTORC2
			ADS.LUSC_ADQ_PRAS40_mTORC1
			ADS.LUSC_ADQ_mTORC2_Akt;
run;





























